version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build
          command: dotnet build

      - run:
          name: Dotnet Publish
          command: dotnet publish -c Release

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Dependencies docker
          command: |
            ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            
      - run:
          name: Docker build
          command: docker build -t mywebapp -f Dockerfile .

      - run:
          name: Docker setup......
          command: |
            TAG="1.0.${CIRCLE_BUILD_NUM}"
            $(aws ecr get-login --no-include-email --region us-east-2)
            docker build -t docker-webapp .
            docker tag docker-webapp:latest cesarreyesa/docker-webapp:$TAG

      - run:
          name: Docker publish
          command: |
            TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker push cesarreyesa/docker-webapp::$TAG
